export const PATHS = {
  login: '/login',
  dashboard: '/dashboard',
  patients: '/patients',
  agenda: '/agenda',
  consultations: '/consultations',
  ordonnances: '/ordonnances',
  prescriptionExamen: '/prescription-examen',
  prescriptionLunettes: '/prescription-lunettes',
  facturation: '/facturation',
  statistiques: '/statistiques',
  parametres: '/parametres',
  utilisateurs: '/utilisateurs',
  forbidden: '/403',
} as const
